{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        env:
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis
        - name: REDIS_PORT
          value: "{{ .Values.redis.service.port }}"
        - name: MONGO_HOST
          value: {{ .Release.Name }}-mongodb
        - name: MONGO_PORT
          value: "{{ .Values.mongodb.service.port }}"
        resources:
{{ toYaml .Values.backend.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}
    component: backend
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    name: ws
  selector:
    app: {{ .Release.Name }}
    component: backend
{{- end }}
