apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
spec:
  selector:
    app: {{.Values.app.name}}
  ports:
    - port: {{.Values.app.port}}
      targetPort: {{.Values.app.port}}
  type: {{.Values.app.type}}

