apiVersion: v1
kind: Pod
metadata:
    name: my-pod-secrets-configmaps
spec:
  containers:
  - name: ip-app
    image: pradeepbrucelee/first:1.0 
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: '/app/volume/configmap'
    - name: secret-volume
      mountPath: '/app/volume/secret'  
  volumes:
  - name: config-volume 
    configMap: 
       name: my-vol-cm
  - name: secret-volume 
    secret:
       secretName: my-vol-secret    
